name: check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Print Go version and environment
        run: |
          printf "Which go: $(which go)\n"
          printf "Go version: $(go version)\n"
      - name: Check go.mod
        run: go mod tidy -diff
